CREATE TABLE `product` (
	`pno` INT(10) NOT NULL AUTO_INCREMENT,
	`pid` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`pname` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`price` INT(10) NULL DEFAULT NULL,
	`description` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`maker` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`category` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`stock` INT(10) NULL DEFAULT NULL,
	`condition` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`pimage` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`quantity` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`pno`) USING BTREE,
	UNIQUE INDEX `pid` (`pid`) USING BTREE
)
ENGINE=InnoDB
;

CREATE TABLE `purchased` (
	`purno` INT(10) NOT NULL AUTO_INCREMENT,
	`pid` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`id` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`pquantity` INT(10) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`address` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`purno`) USING BTREE,
	FOREIGN KEY (`id`) REFERENCES user (`id`),
	FOREIGN KEY (`name`) REFERENCES user (`name`),
	FOREIGN KEY (`email`) REFERENCES user (`email`),
	FOREIGN KEY (`pid`) REFERENCES product (`pid`)
)
ENGINE=InnoDB
;



CREATE TABLE `user` (
	`id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`password` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`email` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`gender` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `name` (`name`) USING BTREE,
	UNIQUE INDEX `email` (`email`) USING BTREE
)
ENGINE=InnoDB
;

